### ISSUE TITLE
source of the equation 

### ISSUE THREAD

**Issue by anitam1992** [cekbote/optimal_uav_placement_and_communication#2]
Very nice code and thanks for upload it. 
i am understanding the following equations   
G(i, j) = (dist - r1 - r2) * w_mot + (r1 + r2) * w_com;
G(i, j) = dist * w_com;
please mention the source of the equation

**Comment by cekbote** [comment]
Hi, you can find the equation in our [paper](https://drive.google.com/file/d/1YbcdqrsDdx-4Iu-4mt2wP0hZ5f6hH7Sp/view?usp=sharing).
